### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by bokkoman**
Purpose:
added prowlarr. That should be standard now in my opinion.

### CODE REVIEW

**Review by bakerboy448 — CHANGES_REQUESTED** [review]
please edit commit message to follow the guide's standards

**Comment by bokkoman** [comment]
@TRaSH- can you please push this?

**Review by BaukeZwart — COMMENTED** [review]
same as #210

**Comment by bakerboy448** [comment]
already complete
https://github.com/TRaSH-Guides/Synology-Templates/pull/210
https://github.com/TRaSH-Guides/Synology-Templates/commit/11abc5c9062f1483993dc8f9e4498d5966f5f139

**Pull request closed without merging**
